spring.application.name=agent
logging.level.org.springframework.ai=DEBUG

spring.ai.bedrock.converse.chat.options.model=global.anthropic.claude-sonnet-4-20250514-v1:0
spring.ai.bedrock.converse.chat.options.max-tokens=4096

# JDBC Memory Configuration
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# RAG Configuration
spring.ai.model.embedding=bedrock-titan
spring.ai.bedrock.titan.embedding.model=amazon.titan-embed-text-v2:0
spring.ai.bedrock.titan.embedding.input-type=text
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1024

spring.ai.mcp.client.toolcallback.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI:}